### ISSUE TITLE
Test application segfaults

### ISSUE THREAD

**Issue by Buanderie** [paladin-t/fiber#1]
Test app segfaults on my x64 Linux (Ubuntu 14.04) dev machine.
Here:
https://imgur.com/jt1Rnx7
And here:
https://imgur.com/Kxgfzuq

It segfaults at:
`fiber_switch(test.fb1);` in test.c

Could not investigate much more

**Comment by paladin-t** [comment]
Thanks for the bug report. I was testing on Rasbian without problem. Now it works as well on my x64 Ubuntu 16.04.
